stages:
  train_linear_regression:
    cmd: python 10/data/scripts/train_model.py
    deps:
    - data/student_combined_cleaned.csv
    outs:
    - models/model.pkl

  train_decision_tree:
    cmd: python 10/data/scripts/train_decision_tree.py
    deps:
    - data/student_combined_cleaned.csv
    outs:
    - models/tree_model.pkl

  train_catboost:
    cmd: python 10/data/scripts/data/train_catboost_full.py
    deps:
    - data/student_combined_cleaned.csv
    - 10/data/scripts/data/train_catboost_full.py
    outs:
    - models/catboost_model_full.cbm

  evaluate_model:
    cmd: python 10/data/scripts/evaluate_model.py
    deps:
    - data/student_combined_cleaned.csv
    - models/model.pkl
    - models/tree_model.pkl
    - models/catboost_model_full.cbm
    outs:
    - eval_results.txt
  train_xgboost:
    cmd: \
